### ISSUE TITLE
feature extraction script missing?

### ISSUE THREAD

**Issue by xianjunxia** [kkoutini/cpjku_dcase19#1]
Dear author,

It seems that the feature extraction python script is missing in this repo. The data_downloader and training script are avaliable. Are there any future updates, thanks

Regards,

**Comment by JiyueWang** [comment]
I have a smililar problem, may I ask how did you fix it?

Traceback (most recent call last):
  File "Q:\cpjku_dcase19-master111\datasets.py", line 441, in __init__
    self.obj = torch.load(xpath)
  File "C:\Anaconda3\envs\cpjku_dcase19\lib\site-packages\torch\serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Anaconda3\envs\cpjku_dcase19\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Anaconda3\envs\cpjku_dcase19\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cached_datasets/d19t1\\tr_mean_452f8f_f1_apd18_stereo_obj.pt'
