### ISSUE TITLE
error different shape

### ISSUE THREAD

**Issue by riyad583h** [kkoutini/cpjku_dcase19#7]
optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: [0.9, 0.999]
    eps: 1e-08
    lr: 0.0001
    weight_decay: 0
)
normalized test!
loading dataset from 'd19t1'
normalizing dataset
attempting to load x from cache at datasets/cached_datasets/d19t1/tr_mean_452f8f_f1_apd18_stereo_obj.pt...
loaded datasets/cached_datasets/d19t1/tr_mean_452f8f_f1_apd18_stereo_obj.pt from cache in 0.000247955322265625 
attempting to load x from cache at datasets/cached_datasets/d19t1/tr_std_452f8f_f1_apd18_stereo_obj.pt...
loaded datasets/cached_datasets/d19t1/tr_std_452f8f_f1_apd18_stereo_obj.pt from cache in 9.322166442871094e-05 
normalized train!
normalized test!
normalized SUB dataset!
loading dataset from 'd19t1_sub'
will load pre-trained model from  pretrained_models/last_model_345.pth
model loaded, predicting...
x: torch.Size([10, 2, 256, 431])
in_c: torch.Size([10, 128, 127, 215])
stage1: torch.Size([10, 128, 15, 26])
stage2: torch.Size([10, 256, 15, 26])
stage3: torch.Size([10, 512, 15, 26])
feed_forward: torch.Size([10, 10, 1, 1])
logit: torch.Size([10, 10])
Traceback (most recent call last):
  File "exp_cp_resnet.py", line 88, in <module>
    sids, propbs = trainer.do_predict("eval",{})
/Downloads/cpjku_dcase19-master/trainer.py", line 783, in do_predict
    for step, (data, sids, _) in enumerate(test_loader):
/miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
/miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
/miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
 miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [2, 256, 431] at entry 0 and [2, 256, 378] at entry 2

**Comment by kkoutini** [comment]
I think this happens because you're evaluting on audios with different lengths. you can either pad and crop the audio clips or set the batch_size to 1 : https://github.com/kkoutini/cpjku_dcase19/blob/eb20fcd36ab3b671c93414f0b543e83cb92cedf0/configs/cp_resnet.json#L58C17-L58C17

**Comment by riyad583h** [comment]
still same error, i just follow ur instruction from readme

**Comment by kkoutini** [comment]
If you're using the eval config, try to change the batch size here:
https://github.com/kkoutini/cpjku_dcase19/blob/eb20fcd36ab3b671c93414f0b543e83cb92cedf0/configs/cp_resnet_eval.json#L77C17-L77C17

**Comment by riyad583h** [comment]
i am using the eval config , i got this one : 
  sids, propbs = trainer.do_predict("eval",{})
  File "/home//Downloads/cpjku_dcase19-master/trainer.py", line 783, in do_predict
    for step, (data, sids, _) in enumerate(test_loader):
  File "/home//miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home//miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home//miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home//miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home//Downloads/cpjku_dcase19-master/datasets.py", line 337, in __getitem__
    x, id, y = self.dataset[index]
  File "/home/Downloads/cpjku_dcase19-master/datasets.py", line 297, in __getitem__
    return torch.load(cpath)
  File "/home/miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home//miniconda3/envs/cpjku_dcase20/lib/python3.7/site-packages/torch/serialization.py", line 780, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 109074 more bytes. The file might be corrupted.
